# Generated by Django 4.0.4 on 2023-04-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignment_student_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student_assigned',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
