# Generated by Django 4.0.4 on 2023-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_assignment_student_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
